---
server:
  port: 8888


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hmozo/pluralsight-spring-cloudconfig-wa-tolls.git
          #username: username
          #password: password
          search-paths:
          - 'station*'
          repos:
            perf:
              pattern:
              - "*/perf"
              uri: https://github.com/hmozo/pluralsight-spring-cloudconfig-wa-tolls-perf.git
              search-paths:
                - 'station*'
        encrypt:
          enabled: false
          
  security:
    user:
      name: pluralsight
      password: pluralsight
  
  
